# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  config.vm.network :hostonly, "192.168.33.11"

  # Assign this VM to a bridged network, allowing you to connect directly to a
  # network using the host's network device. This makes the VM appear as another
  # physical device on your network.
  # config.vm.network :bridged

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  # config.vm.forward_port 80, 8080

  # Share a local folder with the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  # You'll probably want to modify the host target
  config.vm.share_folder "www", "/var/www", "../src", :mount_options => ["dmode=777","fmode=777"]

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding 
  # some recipes and/or roles.
  
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "chef/cookbooks"
    chef.add_recipe("vagrant")
    chef.add_recipe("apache2")
    chef.add_recipe("mysql")
    chef.add_recipe("php")
    chef.add_recipe("memcached")
    chef.add_recipe("phpunit")
    chef.add_recipe("mysql::server")
    chef.add_recipe("php::module_mysql")
    chef.add_recipe("php::module_memcache")
    chef.add_recipe("apache2::mod_php5")
    chef.add_recipe("vagrant::a2ensite_default")
    chef.json = {
      :mysql => {
        :server_root_password => 'root',
        :server_debian_password => 'password',
        :server_repl_password => 'password'
      }
    }
  end
end
